spring.application.name=CoreApartmentService
server.port=7001


spring.datasource.url=jdbc:postgresql://localhost:5432/apartment_complex_db
spring.datasource.username=postgres
spring.datasource.password=postSql@5644
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true